default:
	g++ -DDBUS_API_SUBJECT_TO_CHANGE -I/usr/include/dbus-c++-1 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include  -ldbus-c++-1 -ldbus-1 -I. -I../include -Wall -pedantic -g -O2 -o log logger.cpp -lserial
